'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowLeft, Copy, ExternalLink, ShieldCheck } from 'lucide-react'

type Payment = { public_id: string; recipient_name?: string; amount: string; asset: string; chain: string; destination_address: string; description?: string; status: string; expires_at?: string }
export default function PayPage({ params }: { params: Promise<{ id: string }> }) {
  const [payment, setPayment] = useState<Payment>(); const [error, setError] = useState('')
  useEffect(() => { params.then(({ id }) => fetch(`/api/payments/${id}`).then(r => r.json()).then(d => d.payment ? setPayment(d.payment) : setError(d.error ?? 'Payment not found'))) }, [params])
  if (error) return <main className="grid min-h-screen place-items-center bg-[#0b0d12] px-6 text-white"><div className="text-center"><p className="text-xl">{error}</p><Link href="/" className="mt-5 inline-block text-sm text-[#a6e96b]">Return to ThorPay</Link></div></main>
  if (!payment) return <main className="grid min-h-screen place-items-center bg-[#0b0d12] text-white/50">Loading payment request…</main>
  const expired = payment.status === 'expired'
  return <main className="min-h-screen bg-[#0b0d12] px-6 py-8 text-white"><div className="mx-auto max-w-xl"><Link href="/" className="inline-flex items-center gap-2 text-sm text-white/50"><ArrowLeft data-icon="inline-start" /> ThorPay</Link><section className="mt-12 rounded-3xl border border-white/10 bg-[#151820] p-7"><div className="flex items-center justify-between"><span className="text-xs tracking-widest text-white/40">PAYMENT REQUEST</span><span className={`rounded-full px-3 py-1 text-xs ${expired ? 'bg-red-400/10 text-red-300' : 'bg-[#a6e96b]/10 text-[#a6e96b]'}`}>{expired ? 'EXPIRED' : 'ACTIVE'}</span></div><p className="mt-10 text-sm text-white/45">{payment.recipient_name || 'Someone'} is requesting</p><h1 className="mt-2 text-5xl font-semibold tracking-tight">{payment.amount} <span className="text-2xl text-white/45">{payment.asset}</span></h1>{payment.description && <p className="mt-4 text-white/60">{payment.description}</p>}<div className="mt-8 rounded-2xl border border-white/8 bg-black/15 p-4 text-sm"><p className="text-xs text-white/35">RECEIVING ADDRESS · {payment.chain}</p><p className="mt-2 break-all text-white/70">{payment.destination_address}</p></div>{expired ? <div className="mt-6 rounded-2xl bg-red-400/10 p-4 text-sm text-red-200">This request is no longer accepting payments.</div> : <><h2 className="mt-8 text-lg font-medium">Choose how you want to pay</h2><p className="mt-2 text-sm text-white/45">Select a supported asset. ThorPay will fetch a fresh THORChain quote before you confirm.</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{['BTC','ETH','USDT','RUNE'].map(asset => <button key={asset} className="rounded-2xl border border-white/10 bg-white/[.03] px-4 py-4 text-left hover:border-[#a6e96b]/50"><span className="block text-sm font-medium">{asset}</span><span className="mt-1 block text-xs text-white/35">Select asset</span></button>)}</div><button className="mt-6 w-full rounded-full bg-[#a6e96b] px-5 py-3.5 font-medium text-[#10130d]">Connect wallet to pay {payment.amount} {payment.asset}</button></>}<div className="mt-7 flex items-center justify-center gap-2 text-xs text-white/35"><ShieldCheck data-icon="inline-start" /> Non-custodial · Powered by THORChain</div></section></div></main>
}
